name: Spring Boot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# CHANGE THIS if your pom.xml is in a subfolder (e.g., gameflix-backend)
env:
  PROJECT_DIR: .

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Verify project location (debug)
        run: |
          echo "PWD=$(pwd)"
          ls -la
          test -f pom.xml || (echo "❌ pom.xml not found in $PWD"; exit 1)
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Build with Maven (skip tests)
        run: mvn -B -DskipTests=true clean package
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Show build artifacts (debug)
        run: ls -la target || true
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Build Docker image
        run: docker build -t gameflix-backend:ci .
        working-directory: ${{ env.PROJECT_DIR }}
